# Chapter 2

## Adding and removing data

In [57]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv(
    '../data/earthquakes.csv',
    usecols=[
        'time', 'title', 'place','magType',
        'mag', 'alert', 'tsunami'
    ]
)

In [3]:
df.head()

,alert,mag,magType,place,time,title,tsunami
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0

### Creating new data

In [26]:
df['source'] = 'USGS API'
df.head()

,alert,mag,magType,place,time,title,tsunami,source
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,USGS API
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,USGS API
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,USGS API

In [27]:
df['mag_negative'] = df.mag < 0
df.head()

,alert,mag,magType,place,time,title,tsunami,source,mag_negative
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,USGS API,False
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,USGS API,False
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,USGS API,False

In [28]:
df.place.str.extract(r', (.*$)')[0].sort_values().unique()

array(['Afghanistan', 'Alaska', 'Argentina', 'Arizona', 'Arkansas',
       'Australia', 'Azerbaijan', 'B.C., MX', 'Barbuda', 'Bolivia',
       'Bonaire, Saint Eustatius and Saba ', 'British Virgin Islands',
       'Burma', 'CA', 'California', 'Canada', 'Chile', 'China',
       'Christmas Island', 'Colombia', 'Colorado', 'Costa Rica',
       'Dominican Republic', 'East Timor', 'Ecuador', 'Ecuador region',
       'El Salvador', 'Fiji', 'Greece', 'Greenland', 'Guam', 'Guatemala',
       'Haiti', 'Hawaii', 'Honduras', 'Idaho', 'Illinois', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Italy', 'Jamaica', 'Japan', 'Kansas',
       'Kentucky', 'Kyrgyzstan', 'Martinique', 'Mauritius', 'Mayotte',
       'Mexico', 'Missouri', 'Montana', 'NV', 'Nevada', 'New Caledonia',
       'New Hampshire', 'New Mexico', 'New Zealand', 'Nicaragua',
       'North Carolina', 'Northern Mariana Islands', 'Oklahoma', 'Oregon',
       'Pakistan', 'Papua New Guinea', 'Peru', 'Philippines',
       'Puerto Rico', 'Romania', 'Russia', 'Saint Helena',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Carolina',
       'South Georgia and the South Sandwich Islands',
       'South Sandwich Islands', 'Taiwan', 'Tajikistan', 'Tennessee',
       'Texas', 'Tonga', 'Turkey', 'U.S. Virgin Islands', 'Utah',
       'Uzbekistan', 'Vanuatu', 'Vermont', 'Washington', 'Wyoming',
       'Yemen', nan], dtype=object)

In [29]:
df.place.unique().tolist()

['9km NE of Aguanga, CA',
 '8km NE of Aguanga, CA',
 '10km NW of Avenal, CA',
 '55km ESE of Punta Cana, Dominican Republic',
 '105km W of Talkeetna, Alaska',
 '10km NW of Parkfield, CA',
 '6km NW of The Geysers, CA',
 '219km SSE of Saparua, Indonesia',
 '10km NE of Aguanga, CA',
 '53km SE of Punta Cana, Dominican Republic',
 '120km SSW of Banda Aceh, Indonesia',
 '14km NW of Parkfield, CA',
 '156km WNW of Haines Junction, Canada',
 '2km N of The Geysers, CA',
 '2km S of Maricao, Puerto Rico',
 '57km SSW of Kaktovik, Alaska',
 '4km ENE of Calimesa, CA',
 '61km N of Tierras Nuevas Poniente, Puerto Rico',
 '64km SSW of Salcha, Alaska',
 '4km NW of San Clemente, CA',
 '27km E of Coso Junction, CA',
 '6km SSE of Idyllwild, CA',
 '111km NNW of Arctic Village, Alaska',
 '43km S of Redoubt Volcano, Alaska',
 '86km SW of Anchor Point, Alaska',
 '15km NW of Parkfield, CA',
 '2km WNW of Manhattan, Montana',
 '79km SW of Kaktovik, Alaska',
 '13km E of Hawthorne, Nevada',
 '45km S of Kaktovik, Alaska',
 '83km W of Anchor Point, Alaska',
 '60km S of Cantwell, Alaska',
 '165km NNW of Flying Fish Cove, Christmas Island',
 '95km N of College, Alaska',
 '7km SW of Volcano, Hawaii',
 '6km NW of Lemmon Valley, Nevada',
 '10km ESE of Lincoln, Montana',
 '12km N of Borrego Springs, CA',
 '67km NNE of Arecibo, Puerto Rico',
 '23km SSW of South Dos Palos, CA',
 '13km W of Y, Alaska',
 '6km NNW of Pinnacles, CA',
 '42km WSW of Tonopah, Nevada',
 '65km SSW of Kaktovik, Alaska',
 '78km SW of Kaktovik, Alaska',
 '61km S of Cantwell, Alaska',
 '61km N of Pahrump, Nevada',
 '4km SSW of Carpinteria, CA',
 '242km NNW of Farallon de Pajaros, Northern Mariana Islands',
 '109km NW of Arctic Village, Alaska',
 '17km SE of Volcano, Hawaii',
 '2km WNW of Big Bear City, CA',
 '5km WNW of San Juan Bautista, CA',
 '30km NNW of Santa Barbara Is., CA',
 '131km WNW of Arctic Village, Alaska',
 '22km E of Honaunau-Napoopoo, Hawaii',
 '160km NNW of Nago, Japan',
 '1km SE of Placentia, CA',
 '6km NNE of Banning, CA',
 '18km NW of Parkfield, CA',
 '36km ENE of Big Pine, California',
 '58km NNE of Pahrump, Nevada',
 '70km N of Tierras Nuevas Poniente, Puerto Rico',
 '74km NW of Larsen Bay, Alaska',
 '6km WNW of The Geysers, CA',
 '77km NNW of New Allakaket, Alaska',
 '11km NE of Aguanga, CA',
 '59km NNE of Pahrump, Nevada',
 '13km S of Reno, Nevada',
 '21km ENE of Honaunau-Napoopoo, Hawaii',
 '93km ENE of Kobuk, Alaska',
 '123km NNW of Arctic Village, Alaska',
 '5km NNW of The Geysers, CA',
 '14km NE of East Quincy, California',
 '41km NNW of North Nenana, Alaska',
 '28km N of North Nenana, Alaska',
 '57km SSW of Beatty, Nevada',
 '11km WNW of Sutton-Alpine, Alaska',
 '50km E of Cantwell, Alaska',
 '32km SE of Muisne, Ecuador',
 '150km E of Luganville, Vanuatu',
 '6km S of Palomar Observatory, CA',
 '10km SSE of Redoubt Volcano, Alaska',
 '3km NNE of The Geysers, CA',
 '60km E of Big Pine, California',
 '45km WSW of Big Lake, Alaska',
 '66km SW of Cantwell, Alaska',
 '112km NNW of Arctic Village, Alaska',
 '25km NW of Ester, Alaska',
 '8km ESE of Mammoth Lakes, CA',
 '8km ENE of Aguanga, CA',
 '5km WSW of Anza, CA',
 '10km S of Progreso, B.C., MX',
 '14km ESE of Lincoln, Montana',
 '112km NE of Kodiak, Alaska',
 '35km S of Ester, Alaska',
 '93km WNW of Arctic Village, Alaska',
 '20km WSW of Smith Valley, Nevada',
 '13km S of Verdi, Nevada',
 '93km SW of Kaktovik, Alaska',
 '26km WNW of Volcano, Hawaii',
 '5km WSW of Volcano, Hawaii',
 '262km NW of Ozernovskiy, Russia',
 '22km ENE of Honaunau-Napoopoo, Hawaii',
 '48km NE of Talkeetna, Alaska',
 '52km ESE of Punta Cana, Dominican Republic',
 '69km SW of Kaktovik, Alaska',
 '4km SE of Lake Henshaw, CA',
 '40km NNW of Road Town, British Virgin Islands',
 '13km S of Fern Acres, Hawaii',
 '14km S of Fern Acres, Hawaii',
 '103km NNW of Arctic Village, Alaska',
 '63km SSW of Kaktovik, Alaska',
 '33km N of Beatty, Nevada',
 '90km SW of Kaktovik, Alaska',
 '28km NNW of Packwood, Washington',
 '10km SSE of Beatty, Nevada',
 '45km NW of Talkeetna, Alaska',
 '12km WNW of The Geysers, CA',
 '3km SSW of Maricao, Puerto Rico',
 '3km WSW of Maricao, Puerto Rico',
 '84km SW of Kaktovik, Alaska',
 '4km N of Pacoima, CA',
 '10km ENE of Badger, Alaska',
 '95km SE of Angoram, Papua New Guinea',
 '4km WNW of Mammoth Lakes, CA',
 '9km NNE of Aguanga, CA',
 '21km SSW of La Quinta, CA',
 '57km N of Petersburg, Alaska',
 '2km NNW of Indio, CA',
 '71km SSW of Kaktovik, Alaska',
 '69km S of Beatty, Nevada',
 '5km SW of Anza, CA',
 '15km NW of Pinnacles, CA',
 '80km S of Kaktovik, Alaska',
 '20km SSE of Ronan, Montana',
 '29km ENE of Bridgeport, California',
 '9km ENE of Aguanga, CA',
 '105km NW of Arctic Village, Alaska',
 '104km NW of Talkeetna, Alaska',
 '84km SSW of Kaktovik, Alaska',
 '8km ENE of Mammoth Lakes, CA',
 '7km ESE of Yucaipa, CA',
 '100km WNW of Arctic Village, Alaska',
 '91km W of Willow, Alaska',
 'South of the Fiji Islands',
 '5km WNW of The Geysers, CA',
 '12km SSE of Verdi, Nevada',
 '102km NNE of Kodiak, Alaska',
 '25km E of Bitung, Indonesia',
 '14km S of Leilani Estates, Hawaii',
 '6km NE of Anza, CA',
 '7km NE of Aguanga, CA',
 '49km NW of Cape Yakataga, Alaska',
 '12km S of Mogul, Nevada',
 '5km ESE of Leilani Estates, Hawaii',
 '20km NE of Olancha, CA',
 '8km WNW of The Geysers, CA',
 '88km NNW of Talkeetna, Alaska',
 '93km NNW of Nikiski, Alaska',
 '61km NNE of Pahrump, Nevada',
 '5km S of Idyllwild, CA',
 '6km W of Anza, CA',
 '68km N of Nikiski, Alaska',
 '107km SW of Kaktovik, Alaska',
 '60km N of Pahrump, Nevada',
 '4km E of Banning, CA',
 '37km ENE of Beatty, Nevada',
 '18km NE of Yerington, Nevada',
 '4km E of Indianola, Washington',
 '47km ESE of Beatty, Nevada',
 '11km WNW of Malibu, CA',
 '52km N of Arctic Village, Alaska',
 '38km ENE of Christiansted, U.S. Virgin Islands',
 '64km SSW of Kaktovik, Alaska',
 '21km SW of La Quinta, CA',
 '5km SSE of Mentone, CA',
 '22km NNE of Pahrump, Nevada',
 '15km WSW of Volcano, Hawaii',
 '40km N of Valdez, Alaska',
 '110km NNW of Arctic Village, Alaska',
 '159km SSE of Kotzebue, Alaska',
 '27km NW of Arctic Village, Alaska',
 '92km SE of King Salmon, Alaska',
 '58km WNW of Valdez, Alaska',
 '84km N of San Antonio, Puerto Rico',
 '13km WNW of Toms Place, CA',
 '72km NNW of Arctic Village, Alaska',
 '58km NNW of Arctic Village, Alaska',
 '155km N of Calama, Chile',
 '42km WNW of Sola, Vanuatu',
 '15km WSW of Pisco, Peru',
 '136km SW of Old Crow, Canada',
 '193km N of Qulansiyah, Yemen',
 '11km WSW of Volcano, Hawaii',
 '57km NNW of Arctic Village, Alaska',
 '116km WNW of Arctic Village, Alaska',
 '61km NNW of Arctic Village, Alaska',
 '92km SSW of Kaktovik, Alaska',
 '9km NNW of Pinnacles, CA',
 '18km WSW of Toms Place, CA',
 '56km NNW of Arctic Village, Alaska',
 '1km NE of Pinnacles, CA',
 '70km WNW of Valdez, Alaska',
 '45km NNW of Arctic Village, Alaska',
 '12km SSW of Toms Place, CA',
 "151km S of Severo-Kuril'sk, Russia",
 '34km N of Arctic Village, Alaska',
 '42km NNW of Arctic Village, Alaska',
 '45km N of Arctic Village, Alaska',
 '109km ESE of Holy Cross, Alaska',
 '50km E of Cape Yakataga, Alaska',
 '39km SSW of Qualeys Camp, NV',
 '18km ESE of Anza, CA',
 '41km NNW of Arctic Village, Alaska',
 "236km NNW of Kuril'sk, Russia",
 '6km NNW of The Geysers, CA',
 '13km E of Nueva Concepcion, Guatemala',
 '2km ESE of Home Gardens, CA',
 '44km NNW of Arctic Village, Alaska',
 '13km ESE of Lincoln, Montana',
 '7km E of Cold Springs, Nevada',
 '54km NNW of Arctic Village, Alaska',
 '22km W of Petrolia, CA',
 '7km NW of Pinnacles, CA',
 '43km NNW of Arctic Village, Alaska',
 '27km NNE of Nellis Air Force Base, Nevada',
 '69km WSW of Talkeetna, Alaska',
 '48km NNW of Arctic Village, Alaska',
 '95km SE of King Salmon, Alaska',
 '2km SE of The Geysers, CA',
 '2km WSW of Mammoth Lakes, CA',
 '7km WNW of The Geysers, CA',
 '55km NNW of Arctic Village, Alaska',
 '3km NW of The Geysers, CA',
 '20km WSW of Ferndale, CA',
 '79km W of Anchor Point, Alaska',
 '7km WNW of Tahoe Vista, California',
 '9km WSW of Wrightwood, CA',
 '34km NE of Lucerne Valley, CA',
 '1km N of The Geysers, CA',
 '18km SE of Ridgecrest, CA',
 '122km W of Cantwell, Alaska',
 '65km NE of Sutton-Alpine, Alaska',
 '44km NNW of Los Algodones, B.C., MX',
 '26km N of San Juan, Puerto Rico',
 '4km S of Loyola, CA',
 '11km NNW of Yosemite Lakes, CA',
 '71km NNE of Akutan, Alaska',
 '12km SE of Knik-Fairview, Alaska',
 '6km NNW of Harper, Kansas',
 '74km W of Big Lake, Alaska',
 '3km NNW of The Geysers, CA',
 '94km SW of Anchor Point, Alaska',
 '14km ENE of Redoubt Volcano, Alaska',
 '36km WSW of Big Lake, Alaska',
 '56km N of Punta Cana, Dominican Republic',
 '24km W of Dutch Harbor, Alaska',
 '74km N of Tierras Nuevas Poniente, Puerto Rico',
 '8km SSE of San Juan Bautista, CA',
 '63km ESE of Manjimup, Australia',
 '81km SSW of Arctic Village, Alaska',
 '116km W of Ferndale, CA',
 '118km SSE of King Salmon, Alaska',
 '96km SW of Anchor Point, Alaska',
 '17km ENE of Spanish Springs, Nevada',
 '39km ESE of Bridgeport, California',
 '3km WSW of Tahoe Vista, California',
 '14km SE of Lincoln, Montana',
 '37km NE of Road Town, British Virgin Islands',
 '7km NE of Rohnert Park, CA',
 '57km SE of Warm Springs, Nevada',
 '9km N of North Nenana, Alaska',
 '11km NE of Pinnacles, CA',
 '32km WNW of Nikiski, Alaska',
 '74km SW of Kaktovik, Alaska',
 '57km N of Hatillo, Puerto Rico',
 '26km NE of Jackson, Wyoming',
 '42km ENE of Adak, Alaska',
 '262km SE of Kodiak, Alaska',
 '47km SW of Cantwell, Alaska',
 '2km WNW of The Geysers, CA',
 '12km SSW of Anza, CA',
 '108km NW of Arctic Village, Alaska',
 '54km NW of Carlin, Nevada',
 '42km NNW of Valdez, Alaska',
 '3km SW of Volcano, Hawaii',
 '16km NNE of Valdez, Alaska',
 '32km SE of Leilani Estates, Hawaii',
 '15km E of Fernley, Nevada',
 '7km S of Palomar Observatory, CA',
 '53km SSW of Redoubt Volcano, Alaska',
 'East of the Kuril Islands',
 '5km E of Hennessey, Oklahoma',
 '13km W of Akutan, Alaska',
 '3km E of Ridgely, Tennessee',
 '8km NW of The Geysers, CA',
 '1km E of Juana Diaz, Puerto Rico',
 '115km ESE of Kimbe, Papua New Guinea',
 '67km E of Cape Yakataga, Alaska',
 '284km NNE of Ndoi Island, Fiji',
 '42km W of Talkeetna, Alaska',
 '5km NW of The Geysers, CA',
 '23km ENE of Honaunau-Napoopoo, Hawaii',
 '116km NNW of Arctic Village, Alaska',
 '122km NNW of Arctic Village, Alaska',
 '27km E of Honaunau-Napoopoo, Hawaii',
 '9km NNW of Volcano, Hawaii',
 '11km SSW of Badger, Alaska',
 '252km SE of Kodiak, Alaska',
 '59km WSW of Anchor Point, Alaska',
 '107km NW of Talkeetna, Alaska',
 '6km SW of Valle Vista, CA',
 '25km NW of Rincon, Puerto Rico',
 '16km ENE of Spanish Springs, Nevada',
 '8km WNW of Cobb, CA',
 'Pacific-Antarctic Ridge',
 '54km ENE of Sutton-Alpine, Alaska',
 '12km ENE of Ocotillo Wells, CA',
 '160km SSE of Kotzebue, Alaska',
 '16km N of Inyokern, CA',
 '33km NW of San Antonio, Puerto Rico',
 '23km NW of Parkfield, CA',
 '28km W of Cohoe, Alaska',
 '65km SE of Cantwell, Alaska',
 '33km W of Ester, Alaska',
 '82km E of Bear Creek, Alaska',
 '63km E of Lazy Mountain, Alaska',
 '130km NW of Arctic Village, Alaska',
 '84km E of Bear Creek, Alaska',
 '87km E of Bear Creek, Alaska',
 '12km NE of Little Lake, CA',
 '114km NNW of Talkeetna, Alaska',
 '4km SE of Mammoth Lakes, CA',
 '13km N of Borrego Springs, CA',
 '14km NNE of Mineral, CA',
 '5km NE of Anza, CA',
 '2km NNW of Cabazon, CA',
 '51km NE of Yakutat, Alaska',
 '38km SSW of Nggongi Satu, Indonesia',
 '16km ESE of Pinnacles, CA',
 '10km ENE of Mammoth Lakes, CA',
 '72km SW of Kaktovik, Alaska',
 '83km WNW of Arctic Village, Alaska',
 '29km NNW of Packwood, Washington',
 '9km W of Progreso, B.C., MX',
 '16km E of Seven Trees, CA',
 '86km NW of Arctic Village, Alaska',
 '3km WNW of Mayaguez, Puerto Rico',
 '1km NNW of Ridgely, Tennessee',
 '69km ESE of Cantwell, Alaska',
 '15km ESE of North Logan, Utah',
 '6km W of Cobb, CA',
 '3km ENE of Ridgely, Tennessee',
 '46km ESE of Boca de Yuma, Dominican Republic',
 '22km WSW of Medford, Oklahoma',
 '7km NNE of Little Lake, CA',
 '67km NNE of Redoubt Volcano, Alaska',
 '71km NNE of Punta Cana, Dominican Republic',
 '21km W of Dutch Harbor, Alaska',
 '6km W of Mammoth Lakes, CA',
 '74km NE of Road Town, British Virgin Islands',
 '288km NNE of Ndoi Island, Fiji',
 '29km ESE of Y, Alaska',
 '42km S of Kaktovik, Alaska',
 '54km NNE of Isabela, Puerto Rico',
 '10km S of Tehachapi, CA',
 '152km WNW of Haines Junction, Canada',
 '49km NNE of Yakutat, Alaska',
 '43km WSW of Tanaga Volcano, Alaska',
 '4km NNW of Pinnacles, CA',
 '11km SSE of Portola Valley, CA',
 '16km NE of Little Lake, CA',
 '5km SW of Volcano, Hawaii',
 '57km S of Kaktovik, Alaska',
 '6km E of Pahala, Hawaii',
 '4km NNW of Aratoca, Colombia',
 '18km NW of Grapevine, CA',
 '5km W of Mammoth Lakes, CA',
 '7km W of Mammoth Lakes, CA',
 '6km WNW of Coso Junction, CA',
 '67km ENE of Fallon, Nevada',
 '2km NW of Manhattan, Montana',
 '7km ESE of Asahi, Japan',
 '60km N of Hatillo, Puerto Rico',
 '13km NW of Ludlow, CA',
 '25km SSE of Yerington, Nevada',
 '65km WNW of San Antonio de los Cobres, Argentina',
 '8km S of Idyllwild, CA',
 '15km S of Estacada, Oregon',
 '17km ENE of Lee Vining, CA',
 '10km ESE of Mammoth Lakes, CA',
 '10km E of Mammoth Lakes, CA',
 '1km SE of The Geysers, CA',
 '3km WNW of Manhattan, Montana',
 '54km NNE of Yakutat, Alaska',
 '43km SW of Anchorage, Alaska',
 '142km ESE of McGrath, Alaska',
 '51km NNE of Yakutat, Alaska',
 '108km NNW of Arctic Village, Alaska',
 '9km SSW of Idyllwild, CA',
 '22km SSE of Buckley, Washington',
 '9km W of Akutan, Alaska',
 '128km SE of Kimbe, Papua New Guinea',
 '1km ENE of Colton, CA',
 '84km ENE of Sutton-Alpine, Alaska',
 '9km NNE of Carrizales, Puerto Rico',
 '71km SW of Cantwell, Alaska',
 '103km ESE of King Salmon, Alaska',
 '90km WSW of Cantwell, Alaska',
 '44km WSW of Santa Cruz, Chile',
 '100km N of Arctic Village, Alaska',
 '12km SSE of Corona, CA',
 '6km WNW of Volcano, Hawaii',
 '99km NNW of Arctic Village, Alaska',
 '47km SE of Goldfield, Nevada',
 '30km SE of Alamo, Nevada',
 '93km NNW of Arctic Village, Alaska',
 '101km ESE of King Salmon, Alaska',
 '4km WSW of Volcano, Hawaii',
 '110km N of Larsen Bay, Alaska',
 '6km ENE of Alum Rock, CA',
 '36km NE of Fernley, Nevada',
 '20km E of Morton, Washington',
 '102km ESE of King Salmon, Alaska',
 '15km NE of Little Lake, CA',
 '5km WNW of Cobb, CA',
 '40km W of Pylos, Greece',
 '87km WSW of Healy, Alaska',
 '70km W of Alamo, Nevada',
 '66km S of Kaktovik, Alaska',
 '1km WNW of Lake Henshaw, CA',
 '2km W of Coto Laurel, Puerto Rico',
 '14km E of Tomakomai, Japan',
 '43km WNW of Willow, Alaska',
 '8km ESE of Willow, Alaska',
 '10km ENE of Milpitas, CA',
 '4km E of Mammoth Lakes, CA',
 '10km ESE of Tehachapi, CA',
 '3km N of Colton, CA',
 '3km SW of Anderson Springs, CA',
 '10km W of The Geysers, CA',
 '41km ENE of Healy, Alaska',
 '13km E of Lincoln, Montana',
 '22km NNE of Anchor Point, Alaska',
 '24km E of Y, Alaska',
 '24km NNW of Tehachapi, CA',
 '100km NNW of Arctic Village, Alaska',
 '28km SW of Hawthorne, Nevada',
 '73km NNE of Tonopah, Nevada',
 '103km W of Cantwell, Alaska',
 '4km S of Lilbourn, Missouri',
 '26km E of Honaunau-Napoopoo, Hawaii',
 '101km NW of Talkeetna, Alaska',
 '18km SSE of East Carbon City, Utah',
 '3km SE of Umatilla, Oregon',
 '48km ENE of Adak, Alaska',
 '102km W of Cantwell, Alaska',
 '8km N of Banning, CA',
 '15km W of Toms Place, CA',
 '17km NNW of North Nenana, Alaska',
 '24km NNE of Sterling, Alaska',
 '3km NNE of Espino, Puerto Rico',
 '2km ENE of Pinnacles, CA',
 '93km SE of King Salmon, Alaska',
 '4km SSE of The Geysers, CA',
 '60km NE of Healy, Alaska',
 '16km NNE of Apple Valley, CA',
 '11km S of Talkeetna, Alaska',
 '2km ESE of The Geysers, CA',
 '22km SSW of Healy, Alaska',
 '9km NW of The Geysers, CA',
 '20km SSE of Progreso, B.C., MX',
 '43km ENE of Adak, Alaska',
 '6km ESE of Santa Venetia, CA',
 '12km N of Cabazon, CA',
 '4km SSW of Volcano, Hawaii',
 '70km E of Cape Yakataga, Alaska',
 '70km W of Healy, Alaska',
 '57km NE of Muminobod, Tajikistan',
 '14km W of Toms Place, CA',
 '6km SSE of Ridgely, Tennessee',
 '97km WNW of Arctic Village, Alaska',
 '16km NE of West Yellowstone, Montana',
 '7km WSW of Townsend, Montana',
 '13km NE of Ruby, Alaska',
 '75km NW of Yakutat, Alaska',
 '17km NE of West Yellowstone, Montana',
 '11km NW of Pinnacles, CA',
 '66km S of Cantwell, Alaska',
 '2km W of Anderson Springs, CA',
 '38km W of Anchorage, Alaska',
 '62km E of Sutton-Alpine, Alaska',
 '146km ESE of Petropavlovsk-Kamchatskiy, Russia',
 '19km S of Tallaboa, Puerto Rico',
 '109km NNW of Arctic Village, Alaska',
 '51km NNE of Beatty, Nevada',
 '33km NW of Willow, Alaska',
 '46km SW of Nikolski, Alaska',
 "162km S of Severo-Kuril'sk, Russia",
 '7km NNW of Houston, Alaska',
 '2km SW of Cobb, CA',
 '69km SSW of Kaktovik, Alaska',
 '10km SW of Morongo Valley, CA',
 '25km E of Honaunau-Napoopoo, Hawaii',
 '24km WSW of Cape Yakataga, Alaska',
 '115km NW of Arctic Village, Alaska',
 '100km NW of Larsen Bay, Alaska',
 '63km NNW of Talkeetna, Alaska',
 '43km E of Beatty, Nevada',
 '10km NNW of Anza, CA',
 '43km SW of Beatty, Nevada',
 '50km N of Sutton-Alpine, Alaska',
 '12km NW of Tiptonville, Tennessee',
 '1km WNW of Manhattan, Montana',
 '22km ENE of Healy, Alaska',
 'Northern Mid-Atlantic Ridge',
 '19km WNW of Caldwell, Kansas',
 '66km SE of Whittier, Alaska',
 'Off the west coast of northern Sumatra',
 '2km WNW of Volcano, Hawaii',
 '66km NNE of Yakutat, Alaska',
 '74km WSW of Tok, Alaska',
 '13km W of Toms Place, CA',
 '55km NE of Badger, Alaska',
 '51km WSW of Kasiguncu, Indonesia',
 '54km NNE of North Pole, Alaska',
 '17km SSW of Big Lake, Alaska',
 '11km NW of Kingsbury, Nevada',
 '6km NW of Anza, CA',
 '9km E of Moreno Valley, CA',
 '50km ENE of Big Pine, California',
 '133km ESE of Kimbe, Papua New Guinea',
 '2km N of Placentia, CA',
 '2km NNE of Placentia, CA',
 '22km N of Ridgecrest, CA',
 '49km E of Beatty, Nevada',
 '28km SSW of Nephi, Utah',
 '111km NNW of San Antonio, Puerto Rico',
 '19km ESE of Anthony, Kansas',
 '44km N of Isabela, Puerto Rico',
 '102km NE of Punta Cana, Dominican Republic',
 '5km ESE of Indios, Puerto Rico',
 '97km SSE of Nikolski, Alaska',
 '9km NNE of Beaumont, CA',
 '43km SSW of Cantwell, Alaska',
 '5km W of Cobb, CA',
 '26km ESE of Honaunau-Napoopoo, Hawaii',
 '63km N of Pahrump, Nevada',
 '113km NNW of Arctic Village, Alaska',
 '13km ESE of Viola, CA',
 '64km N of Pahrump, Nevada',
 '2km NNE of Lake Henshaw, CA',
 '53km E of Beatty, Nevada',
 '7km SE of Mammoth Lakes, CA',
 '56km WNW of Valdez, Alaska',
 '1km W of Manhattan, Montana',
 '58km E of Beatty, Nevada',
 '22km E of Eatonville, Washington',
 '51km W of Tanaga Volcano, Alaska',
 '8km W of Newport Beach, CA',
 '11km SSE of Volcano, Hawaii',
 '3km WSW of Greenville, California',
 '31km WNW of Adak, Alaska',
 '9km N of Cabazon, CA',
 '5km S of Newcastle, Oklahoma',
 '104km NNW of Larsen Bay, Alaska',
 '23km N of Ridgecrest, CA',
 '5km WSW of Darrington, Washington',
 '121km NW of Arctic Village, Alaska',
 '66km SSE of Nikolski, Alaska',
 '225km SW of Ndoi Island, Fiji',
 '139km WSW of Naze, Japan',
 '6km ESE of Mammoth Lakes, CA',
 '163km N of Charlotte Amalie, U.S. Virgin Islands',
 '1km ENE of Mammoth Lakes, CA',
 '13km SW of Leilani Estates, Hawaii',
 "163km S of Severo-Kuril'sk, Russia",
 '6km SSE of Sudden Valley, Washington',
 '5km SE of Mammoth Lakes, CA',
 '83km NNW of Nikiski, Alaska',
 '22km N of Summerlin South, Nevada',
 '108km NW of Talkeetna, Alaska',
 '28km N of Beaver, Utah',
 '30km N of Beaver, Utah',
 '17km W of Imperial, CA',
 '0km WNW of Mammoth Lakes, CA',
 '10km S of Idyllwild, CA',
 '1km SW of Enoch, Utah',
 '42km SW of Beatty, Nevada',
 '47km ENE of Adak, Alaska',
 '34km NW of Stovepipe Wells, CA',
 '89km WNW of Arctic Village, Alaska',
 '106km NW of Talkeetna, Alaska',
 '11km W of Akutan, Alaska',
 '10km SSE of Desert Aire, Washington',
 '2km WSW of Enoch, Utah',
 '24km NW of West Yellowstone, Montana',
 '81km NNW of Arctic Village, Alaska',

In [37]:
df['parsed_place'] = (df
                        .place
                        .str.replace(r'.* of ', '', regex=True)
                        .str.replace(r'CA$', 'California', regex=True)
                        .str.replace(r'NV$', 'Nevada', regex=True)
                        .str.replace(r'MX$', 'Mexico', regex=True)
                        .str.replace(r' region$', '', regex=True)
                        .str.replace('northern ', '')
                        .str.replace('Fiji Islands', 'Fiji')
                        .str.replace(r'^.*, ', '', regex=True)
                        .str.strip()
                    )

In [38]:
df.parsed_place

0        California
1        California
2        California
3        California
4        California
           ...
9327     California
9328     California
9329    Puerto Rico
9330     California
9331     California
Name: parsed_place, Length: 9332, dtype: object

In [39]:
df.query('parsed_place.str.contains("northern")')

Empty DataFrame
Columns: [alert, mag, magType, place, time, title, tsunami, source, mag_negative, parsed_place]
Index: []

In [40]:
df.parsed_place.sort_values().unique().tolist()

['Afghanistan',
 'Alaska',
 'Argentina',
 'Arizona',
 'Arkansas',
 'Ascension Island',
 'Australia',
 'Azerbaijan',
 'Balleny Islands',
 'Barbuda',
 'Bolivia',
 'British Virgin Islands',
 'Burma',
 'California',
 'Canada',
 'Carlsberg Ridge',
 'Central East Pacific Rise',
 'Central Mid-Atlantic Ridge',
 'Chile',
 'China',
 'Christmas Island',
 'Colombia',
 'Colorado',
 'Costa Rica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'El Salvador',
 'Fiji',
 'Greece',
 'Greenland',
 'Guam',
 'Guatemala',
 'Haiti',
 'Hawaii',
 'Honduras',
 'Idaho',
 'Illinois',
 'India',
 'Indian Ocean Triple Junction',
 'Indonesia',
 'Iran',
 'Iraq',
 'Italy',
 'Jamaica',
 'Japan',
 'Kansas',
 'Kentucky',
 'Kuril Islands',
 'Kyrgyzstan',
 'Martinique',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Mid-Indian Ridge',
 'Missouri',
 'Montana',
 'Nevada',
 'New Caledonia',
 'New Hampshire',
 'New Mexico',
 'New Zealand',
 'Nicaragua',
 'North Carolina',
 'Northern East Pacific Rise',
 'Northern Mariana Islands',
 'Northern Mid-Atlantic Ridge',
 'Oklahoma',
 'Oregon',
 'Pacific-Antarctic Ridge',
 'Pakistan',
 'Papua New Guinea',
 'Peru',
 'Philippines',
 'Prince Edward Islands',
 'Puerto Rico',
 'Romania',
 'Russia',
 'Saint Eustatius and Saba',
 'Saint Helena',
 'Socotra',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Carolina',
 'South Georgia and the South Sandwich Islands',
 'South Sandwich Islands',
 'Southeast Indian Ridge',
 'Southern East Pacific Rise',
 'Southern Mid-Atlantic Ridge',
 'Southwest Indian Ridge',
 'Sumatra',
 'Taiwan',
 'Tajikistan',
 'Tennessee',
 'Texas',
 'Tonga',
 'Turkey',
 'U.S. Virgin Islands',
 'Utah',
 'Uzbekistan',
 'Vanuatu',
 'Vermont',
 'Washington',
 'Western Indian-Antarctic Ridge',
 'Western Xizang',
 'Wyoming',
 'Yemen',
 'the Fiji',
 'the Kermadec Islands',
 'the Kuril Islands',
 'the Queen Charlotte Islands',
 'the South Sandwich Islands']

In [42]:
df.assign(
    in_ca=df.parsed_place.str.endswith('California'),
    in_alaska=df.parsed_place.str.endswith('Alaska'),
    neither=lambda x: ~x.in_ca & ~x.in_alaska
).sample(5, random_state=0)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,in_ca,in_alaska,neither
7207,NaN,4.80,mwr,"73km SSW of Masachapa, Nicaragua",1537749595210,"M 4.8 - 73km SSW of Masachapa, Nicaragua",0,USGS API,False,Nicaragua,False,False,True
4755,NaN,1.09,ml,"28km NNW of Packwood, Washington",1538227540460,"M 1.1 - 28km NNW of Packwood, Washington",0,USGS API,False,Washington,False,False,True
4595,NaN,1.80,ml,"77km SSW of Kaktovik, Alaska",1538259609862,"M 1.8 - 77km SSW of Kaktovik, Alaska",0,USGS API,False,Alaska,False,True,False
3566,NaN,1.50,ml,"102km NW of Arctic Village, Alaska",1538464751822,"M 1.5 - 102km NW of Arctic Village, Alaska",0,USGS API,False,Alaska,False,True,False
2182,NaN,0.90,ml,"26km ENE of Pine Valley, CA",1538801713880,"M 0.9 - 26km ENE of Pine Valley, CA",0,USGS API,False,California,True,False,False

In [43]:
tsunami = df[df.tsunami == 1]
no_tsunami = df[df.tsunami == 0]

In [44]:
tsunami.shape, no_tsunami.shape

((61, 10), (9271, 10))

In [45]:
pd.concat([tsunami, no_tsunami]).shape

(9332, 10)

In [46]:
tsunami.append(no_tsunami).shape
# Note:  he frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\tmadsen\AppData\Local\Temp\ipykernel_25400\1630389451.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tsunami.append(no_tsunami).shape

(9332, 10)

In [53]:
additional_columns = pd.read_csv(
    '../data/earthquakes.csv',
    usecols=['tz', 'felt', 'ids']
)

In [58]:
np.mean(additional_columns.index == df.index)

1.0

In [48]:
pd.concat([df.head(2), additional_columns.head(2)], axis=1)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,felt,ids,tz
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California,NaN,",ci37389218,",-480.0
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California,NaN,",ci37389202,",-480.0

In [50]:
additional_columns = pd.read_csv(
    '../data/earthquakes.csv',
    usecols=['tz', 'felt', 'ids', 'time'],
    index_col='time'
)

In [51]:
pd.concat([df.head(2), additional_columns.head(2)], axis=1)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,felt,ids,tz
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1.539475e+12,"M 1.4 - 9km NE of Aguanga, CA",0.0,USGS API,False,California,NaN,NaN,NaN
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1.539475e+12,"M 1.3 - 9km NE of Aguanga, CA",0.0,USGS API,False,California,NaN,NaN,NaN
1539475168010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",ci37389218,",-480.0
1539475129610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",ci37389202,",-480.0

In [52]:
pd.concat(
    [
        tsunami.head(2),
        no_tsunami.head(2).assign(type='earthquake')
    ],
    join='inner', ignore_index=True
)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place
0,NaN,5.00,mww,"165km NNW of Flying Fish Cove, Christmas Island",1539459504090,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...",1,USGS API,False,Christmas Island
1,green,6.70,mww,"262km NW of Ozernovskiy, Russia",1539429023560,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,USGS API,False,Russia
2,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
3,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California

In [59]:
df.head()

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,USGS API,False,California
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,USGS API,False,California

### Deleting unwanted data

In [60]:
del df['source']
df.columns

Index(['alert', 'mag', 'magType', 'place', 'time', 'title', 'tsunami',
       'mag_negative', 'parsed_place'],
      dtype='object')

In [66]:
try:
    del df['source']
except KeyError:
    print("column does not exist")

column does not exist

In [67]:
mag_negative = df.pop('mag_negative')
df.columns

Index(['alert', 'mag', 'magType', 'place', 'time', 'title', 'tsunami',
       'parsed_place'],
      dtype='object')

In [68]:
mag_negative.value_counts()

False    8841
True      491
Name: mag_negative, dtype: int64

In [69]:
np.mean(mag_negative.index == df.index)

1.0

In [70]:
df[mag_negative].head()

,alert,mag,magType,place,time,title,tsunami,parsed_place
39,NaN,-0.10,ml,"6km NW of Lemmon Valley, Nevada",1539458844506,"M -0.1 - 6km NW of Lemmon Valley, Nevada",0,Nevada
49,NaN,-0.10,ml,"6km NW of Lemmon Valley, Nevada",1539455017464,"M -0.1 - 6km NW of Lemmon Valley, Nevada",0,Nevada
135,NaN,-0.40,ml,"10km SSE of Beatty, Nevada",1539422175717,"M -0.4 - 10km SSE of Beatty, Nevada",0,Nevada
161,NaN,-0.02,md,"20km SSE of Ronan, Montana",1539412475360,"M -0.0 - 20km SSE of Ronan, Montana",0,Montana
198,NaN,-0.20,ml,"60km N of Pahrump, Nevada",1539398340822,"M -0.2 - 60km N of Pahrump, Nevada",0,Nevada

In [71]:
df.drop([0,1]).head(2)

,alert,mag,magType,place,time,title,tsunami,parsed_place
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,California
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,California

In [72]:
cols_to_drop = [
    col for col in df.columns
    if col not in [
        'alert', 'mag', 'title', 'time', 'tsunami'
    ]
]
df.drop(columns=cols_to_drop).head()

  alert   mag           time                          title  tsunami
0   NaN  1.35  1539475168010  M 1.4 - 9km NE of Aguanga, CA        0
1   NaN  1.29  1539475129610  M 1.3 - 9km NE of Aguanga, CA        0
2   NaN  3.42  1539475062610  M 3.4 - 8km NE of Aguanga, CA        0
3   NaN  0.44  1539474978070  M 0.4 - 9km NE of Aguanga, CA        0
4   NaN  2.16  1539474716050  M 2.2 - 10km NW of Avenal, CA        0

In [74]:
df.drop(columns=cols_to_drop).equals(
    df.drop(cols_to_drop, axis=1)
)

True

## Summary